name: "recsys-filebeat"
logging.metrics.enabled: false
xpack.security.enabled: false
xpack.monitoring.enabled: false
setup.ilm.enabled: false
setup.template.enabled: false

filebeat.inputs:
- type: log
  scan_frequency: 1s
  enabled: true
  paths:
    - /recsys_service/recsys_service.log
  fields:
    - service: recsys_service
  fields_under_root: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "recsys-service"
