name: Code style
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: "Setup python"
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - run: pip install -r requirements-dev.txt
      - run: flake8 .
      - run: isort . --check --diff
      - run: pylint service
      - run: pylint src
